import yaml
import sys
import os
from pathlib import Path
from typing import Any

TEMPLATE_HEADER = '''"""Generated by Semantic Runtime Translator v0.2.0"""
import bpy
import math
import random


def clean_scene():
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete(use_global=False)
    for material in bpy.data.materials:
        bpy.data.materials.remove(material)
    for light in bpy.data.lights:
        bpy.data.lights.remove(light)


def ensure_material(name: str, mat_type: str):
    mat = bpy.data.materials.new(name=name)
    mat.use_nodes = True
    nodes = mat.node_tree.nodes
    links = mat.node_tree.links
    for node in nodes:
        nodes.remove(node)
    if mat_type == "wood":
        tex = nodes.new(type="ShaderNodeTexWave")
        tex.wave_type = "BANDS"
        tex.bands_direction = "X"
        noise = nodes.new(type="ShaderNodeTexNoise")
        noise.inputs["Scale"].default_value = 5.0
        color = nodes.new(type="ShaderNodeBsdfPrincipled")
        color.inputs["Base Color"].default_value = (0.6, 0.35, 0.1, 1)
        color.inputs["Roughness"].default_value = 0.7
        output = nodes.new(type="ShaderNodeOutputMaterial")
        links.new(tex.outputs["Fac"], color.inputs["Roughness"])
        links.new(color.outputs["BSDF"], output.inputs["Surface"])
    elif mat_type == "marble":
        tex = nodes.new(type="ShaderNodeTexBrick")
        tex.brick_color = (0.9, 0.88, 0.85, 1)
        tex.mortar_color = (0.5, 0.48, 0.45, 1)
        tex.inputs["Scale"].default_value = 2.0
        color = nodes.new(type="ShaderNodeBsdfPrincipled")
        color.inputs["Base Color"].default_value = (0.95, 0.93, 0.9, 1)
        color.inputs["Roughness"].default_value = 0.3
        output = nodes.new(type="ShaderNodeOutputMaterial")
        links.new(tex.outputs["Color"], color.inputs["Base Color"])
        links.new(color.outputs["BSDF"], output.inputs["Surface"])
    else:
        color = nodes.new(type="ShaderNodeBsdfPrincipled")
        color.inputs["Base Color"].default_value = (0.5, 0.5, 0.5, 1)
        output = nodes.new(type="ShaderNodeOutputMaterial")
        links.new(color.outputs["BSDF"], output.inputs["Surface"])
    return mat


'''

TEMPLATE_FOOTER = """
clean_scene()
run()
"""


def resolve_target(ref: dict | None, context: dict) -> str:
    if ref is None:
        return ""
    t = ref.get("type", "name")
    v = ref.get("value", "")
    if t == "name":
        return v
    if t == "id":
        return context.get("resolved_names", {}).get(v, v)
    if t == "description":
        resolved = context.get("resolved_descriptions", {}).get(v, v)
        return resolved
    return v


def generate_material_lookup(materials: list[str]) -> str:
    lines = []
    for mat in materials:
        safe = mat.replace(" ", "_")
        lines.append(f'    {safe} = ensure_material("{mat}", "{mat.lower()}")')
    return "\n".join(lines)


def gen_create_object(params: dict, ctx: dict) -> list[str]:
    obj_type = params.get("object_type", "cube")
    name = params.get("name", "Object")
    loc = params.get("location", [0, 0, 0])
    rot = params.get("rotation", [0, 0, 0])
    scale = params.get("scale", [1, 1, 1])
    ctx["last_created"] = name
    lines = []
    if obj_type == "cube":
        lines.append(f'    bpy.ops.mesh.primitive_cube_add(location=({loc[0]}, {loc[1]}, {loc[2]}))')
    elif obj_type == "cone":
        lines.append(f'    bpy.ops.mesh.primitive_cone_add(location=({loc[0]}, {loc[1]}, {loc[2]}))')
    elif obj_type == "cylinder":
        lines.append(f'    bpy.ops.mesh.primitive_cylinder_add(location=({loc[0]}, {loc[1]}, {loc[2]}))')
    elif obj_type == "plane":
        lines.append(f'    bpy.ops.mesh.primitive_plane_add(location=({loc[0]}, {loc[1]}, {loc[2]}))')
    else:
        lines.append(f'    bpy.ops.mesh.primitive_cube_add(location=({loc[0]}, {loc[1]}, {loc[2]}))')
    lines.append(f'    obj = bpy.context.active_object')
    lines.append(f'    obj.name = "{name}"')
    if rot != [0, 0, 0]:
        lines.append(f'    obj.rotation_euler = ({rot[0]}, {rot[1]}, {rot[2]})')
    if scale != [1, 1, 1]:
        lines.append(f'    obj.scale = ({scale[0]}, {scale[1]}, {scale[2]})')
    return lines


def gen_assign_material(params: dict, ctx: dict) -> list[str]:
    target = resolve_target(params.get("target_ref"), ctx)
    mat_name = params.get("material_name", "Material")
    mat_type = params.get("material_type", "")
    if not target:
        target = ctx.get("last_created", "Object")
    lines = [
        f'    mat = ensure_material("{mat_name}", "{mat_type}")',
    ]
    if target.startswith("جميع "):
        prefix = target.replace("جميع ", "")
        lines.append(f'    for obj in bpy.data.objects:')
        lines.append(f'        if obj.type == "MESH" and obj.name.startswith("{prefix}"):')
        lines.append(f'            obj.data.materials.clear()')
        lines.append(f'            obj.data.materials.append(mat)')
    else:
        lines.append(f'    if "{target}" in bpy.data.objects:')
        lines.append(f'        bpy.data.objects["{target}"].data.materials.clear()')
        lines.append(f'        bpy.data.objects["{target}"].data.materials.append(mat)')
    return lines


def gen_add_light(params: dict, ctx: dict) -> list[str]:
    lt = params.get("light_type", "POINT")
    name = params.get("name", "Light")
    loc = params.get("location", [0, 0, 0])
    rot = params.get("rotation", [0, 0, 0])
    energy = params.get("energy", 100)
    color = params.get("color", [1, 1, 1])
    lines = [
        f'    bpy.ops.object.light_add(type="{lt}", location=({loc[0]}, {loc[1]}, {loc[2]}))',
        f'    light_obj = bpy.context.active_object',
        f'    light_obj.name = "{name}"',
        f'    light_obj.data.energy = {energy}',
        f'    light_obj.data.color = ({color[0]}, {color[1]}, {color[2]})',
    ]
    if rot != [0, 0, 0]:
        lines.append(f'    light_obj.rotation_euler = ({rot[0]}, {rot[1]}, {rot[2]})')
    return lines


def gen_set_camera(params: dict, ctx: dict) -> list[str]:
    target = resolve_target(params.get("target_ref"), ctx)
    angle_h = params.get("angle_horizontal", 0)
    angle_v = params.get("angle_vertical", 0)
    dist = params.get("distance_from_target", 5)
    lines = [
        f'    bpy.ops.object.camera_add()',
        f'    cam = bpy.context.active_object',
        f'    cam.name = "Camera"',
        f'    bpy.context.scene.camera = cam',
    ]
    if target and target in bpy.data.objects:
        lines.append(f'    target_obj = bpy.data.objects["{target}"]')
        lines.append(f'    import math')
        rad_h = math.radians(angle_h) if isinstance(angle_h, (int, float)) and angle_h > 6.3 else angle_h
        lines.append(f'    cam.location = (target_obj.location.x + {dist} * math.sin({rad_h}), target_obj.location.y + {dist} * math.cos({rad_h}), target_obj.location.z + {math.sin(math.radians(angle_v)) if angle_v else 0})')
    else:
        lines.append(f'    cam.location = ({dist}, -{dist}, {dist})')
    lines.append(f'    cam.rotation_euler = (math.radians(54.7), 0, math.radians(45))')
    return lines


def gen_analyze_scene(params: dict, ctx: dict) -> list[str]:
    analysis = params.get("analysis_type", "find_target")
    desc = params.get("description", "")
    lines = [f'    # analyze_scene: {analysis} — "{desc}"']
    if "find_target" in analysis:
        if "أمام" in desc or "أقرب" in desc:
            lines.append(f'    # heuristic: find object closest to camera')
            lines.append(f'    cam = bpy.context.scene.camera')
            lines.append(f'    min_dist = float("inf")')
            lines.append(f'    front_obj = None')
            lines.append(f'    for obj in bpy.context.scene.objects:')
            lines.append(f'        if obj.type == "MESH" and obj != cam:')
            lines.append(f'            d = (obj.location - cam.location).length if cam else obj.location.length')
            lines.append(f'            if d < min_dist: min_dist, front_obj = d, obj')
            lines.append(f'    ctx["resolved_descriptions"]["الكائن الأمامي"] = front_obj.name if front_obj else ""')
        elif "أرض" in desc or "سطح" in desc:
            lines.append(f'    # heuristic: find object at lowest Y or named floor/ground')
            lines.append(f'    floor_obj = None')
            lines.append(f'    for obj in bpy.context.scene.objects:')
            lines.append(f'        if obj.type == "MESH" and ("floor" in obj.name.lower() or "ground" in obj.name.lower() or "ارض" in obj.name.lower()):')
            lines.append(f'            floor_obj = obj; break')
            lines.append(f'    if not floor_obj:')
            lines.append(f'        for obj in bpy.context.scene.objects:')
            lines.append(f'            if obj.type == "MESH": floor_obj = obj; break')
            lines.append(f'    ctx["resolved_descriptions"]["الكائن الأرضي"] = floor_obj.name if floor_obj else ""')
            lines.append(f'    ctx["resolved_descriptions"]["السطح الأرضي"] = floor_obj.name if floor_obj else ""')
        elif "إضاء" in desc or "مصادر" in desc:
            lines.append(f'    # heuristic: find all light objects')
            lines.append(f'    ctx["resolved_descriptions"]["جميع مصادر الإضاءة"] = "all_lights"')
            lines.append(f'    ctx["light_sources_found"] = [o for o in bpy.context.scene.objects if o.type == "LIGHT"]')
        elif "أبرز" in desc or "مركز" in desc:
            lines.append(f'    # heuristic: largest mesh object')
            lines.append(f'    main_obj = max((o for o in bpy.context.scene.objects if o.type == "MESH"), key=lambda o: o.dimensions.length, default=None)')
            lines.append(f'    ctx["resolved_descriptions"]["الكائن الأبرز أو المركزي في المشهد"] = main_obj.name if main_obj else ""')
    elif "hardware" in analysis:
        lines.append(f'    # heuristic: detect render capability')
        lines.append(f'    ctx["gpu_available"] = True')
        lines.append(f'    ctx["suggested_engine"] = "EEVEE"')
    elif "lighting" in analysis:
        lines.append(f'    # heuristic: measure lighting')
        lines.append(f'    ctx["lighting_temperature_estimate"] = 3500')
    elif "check" in analysis:
        lines.append(f'    # heuristic: verify lighting result')
        lines.append(f'    print("Verification: lighting analysis complete (interpretive)")')
    return lines


def gen_modify_world(params: dict, ctx: dict) -> list[str]:
    strength = params.get("strength", 1.0)
    color = params.get("color", [1, 1, 1])
    return [
        f'    bpy.context.scene.world.use_nodes = True',
        f'    bg = bpy.context.scene.world.node_tree.nodes.get("Background")',
        f'    if bg:',
        f'        bg.inputs["Strength"].default_value = {strength}',
        f'        bg.inputs["Color"].default_value = ({color[0]}, {color[1]}, {color[2]}, 1)',
    ]


def gen_adjust_scene_temperature(params: dict, ctx: dict) -> list[str]:
    method = params.get("method", "color_temperature")
    value = params.get("value", "warm")
    color_temp = params.get("light_color_temp", 3500)
    bg_color = params.get("background_color", [1, 0.85, 0.6])
    lines = [f'    # adjust_scene_temperature: {value} ({color_temp}K)']
    lines.append(f'    bpy.context.scene.world.use_nodes = True')
    lines.append(f'    bg = bpy.context.scene.world.node_tree.nodes.get("Background")')
    if value == "warm":
        lines.append(f'    if bg: bg.inputs["Color"].default_value = ({bg_color[0]}, {bg_color[1]}, {bg_color[2]}, 1)')
        lines.append(f'    for light in bpy.data.lights:')
        lines.append(f'        light.color = (1.0, 0.85, 0.6)')
        lines.append(f'        light.energy = light.energy * 0.8')
    elif value == "cold":
        lines.append(f'    if bg: bg.inputs["Color"].default_value = ({bg_color[0]}, {bg_color[1]}, {bg_color[2]}, 1)')
        lines.append(f'    for light in bpy.data.lights:')
        lines.append(f'        light.color = (0.3, 0.4, 0.8)')
    return lines


def gen_adjust_light_color(params: dict, ctx: dict) -> list[str]:
    color = params.get("color", [1, 1, 1])
    multiplier = params.get("energy_multiplier", 1.0)
    target = resolve_target(params.get("target_ref"), ctx)
    lines = [f'    # adjust_light_color']
    if target == "all_lights" or target == "جميع مصادر الإضاءة":
        lines.append(f'    for light in bpy.data.lights:')
        lines.append(f'        light.color = ({color[0]}, {color[1]}, {color[2]})')
        lines.append(f'        light.energy = light.energy * {multiplier}')
    else:
        lines.append(f'    if "{target}" in bpy.data.objects:')
        lines.append(f'        obj = bpy.data.objects["{target}"]')
        lines.append(f'        if obj.type == "LIGHT":')
        lines.append(f'            obj.data.color = ({color[0]}, {color[1]}, {color[2]})')
        lines.append(f'            obj.data.energy = obj.data.energy * {multiplier}')
    return lines


def gen_distribute_random(params: dict, ctx: dict) -> list[str]:
    count = params.get("count", 10)
    obj_type = params.get("object_type", "cube")
    scale_range = params.get("scale_range", [0.1, 0.3])
    rot_range = params.get("rotation_range", [0, 6.2832])
    area = params.get("distribution_area", {})
    center = area.get("center", [0, 0, 0])
    size = area.get("size", [4, 4])
    seed = params.get("random_seed")
    lines = [
        f'    if {seed} is not None: random.seed({seed})',
        f'    for _ in range({count}):',
        f'        x = random.uniform({center[0]} - {size[0]}/2, {center[0]} + {size[0]}/2)',
        f'        z = random.uniform({center[1]} - {size[1]}/2, {center[1]} + {size[1]}/2)' if len(area.get("size", [4, 4])) > 1 else f'        z = 0',
        f'        y = random.uniform({center[2]} - {size[1]}/2, {center[2]} + {size[1]}/2)',
        f'        bpy.ops.mesh.primitive_cube_add(location=(x, y, z))' if obj_type == "cube" else f'        bpy.ops.mesh.primitive_cube_add(location=(x, y, z))',
        f'        obj = bpy.context.active_object',
        f'        s = random.uniform({scale_range[0]}, {scale_range[1]})',
        f'        obj.scale = (s, s, s)',
    ]
    if rot_range:
        lines.append(f'        obj.rotation_euler = (random.uniform({rot_range[0]}, {rot_range[1]}), random.uniform({rot_range[0]}, {rot_range[1]}), random.uniform({rot_range[0]}, {rot_range[1]}))')
    return lines


def gen_configure_render(params: dict, ctx: dict) -> list[str]:
    engine = params.get("engine", "EEVEE")
    samples = params.get("samples", 32)
    res_x = params.get("resolution_x", 1280)
    res_y = params.get("resolution_y", 720)
    denoise = params.get("use_denoising", True)
    fmt = params.get("output_format", "PNG")
    quality = params.get("quality", 80)
    lines = [
        f'    bpy.context.scene.render.engine = "{engine}"',
        f'    bpy.context.scene.render.resolution_x = {res_x}',
        f'    bpy.context.scene.render.resolution_y = {res_y}',
        f'    bpy.context.scene.eevee.taa_samples = {samples} if "{engine}" == "EEVEE" else {samples}',
        f'    bpy.context.scene.render.image_settings.file_format = "{fmt}"',
        f'    bpy.context.scene.render.image_settings.quality = {quality}',
    ]
    if denoise:
        lines.append(f'    bpy.context.scene.eevee.use_denoising = True')
    return lines


def gen_enable_depth_of_field(params: dict, ctx: dict) -> list[str]:
    target = resolve_target(params.get("target_ref"), ctx)
    fstop = params.get("aperture_fstop", 2.8)
    blades = params.get("aperture_blades", 6)
    lines = [
        f'    cam = bpy.context.scene.camera',
        f'    if cam:',
        f'        cam.data.dof.use_dof = True',
        f'        cam.data.dof.aperture_fstop = {fstop}',
        f'        cam.data.dof.aperture_blades = {blades}',
    ]
    if target and target != "":
        lines.append(f'        if "{target}" in bpy.data.objects:')
        lines.append(f'            cam.data.dof.focus_object = bpy.data.objects["{target}"]')
    return lines


def gen_replace_material(params: dict, ctx: dict) -> list[str]:
    target = resolve_target(params.get("target_ref"), ctx)
    new_mat = params.get("new_material_name", "Material")
    new_type = params.get("new_material_type", "")
    if not target:
        target = ctx.get("last_created", "Object")
    safe = new_mat.replace(" ", "_")
    return [
        f'    mat = ensure_material("{new_mat}", "{new_type}")',
        f'    if "{target}" in bpy.data.objects:',
        f'        bpy.data.objects["{target}"].data.materials.clear()',
        f'        bpy.data.objects["{target}"].data.materials.append(mat)',
    ]


TRANSFORM_GENERATORS = {
    "create_object": gen_create_object,
    "assign_material": gen_assign_material,
    "replace_material": gen_replace_material,
    "add_light": gen_add_light,
    "set_camera": gen_set_camera,
    "enable_depth_of_field": gen_enable_depth_of_field,
    "analyze_scene": gen_analyze_scene,
    "modify_world_settings": gen_modify_world,
    "adjust_scene_temperature": gen_adjust_scene_temperature,
    "adjust_light_color": gen_adjust_light_color,
    "distribute_objects_randomly": gen_distribute_random,
    "configure_render": gen_configure_render,
}


def load_yaml_from_md(path: str) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        text = f.read()
    start = text.find("```yaml")
    end = text.find("```", start + 7)
    if start != -1 and end != -1:
        body = text[start + 7:end].strip()
        return yaml.safe_load(body)
    return yaml.safe_load(text)


def translate(task_path: str) -> str:
    task = load_yaml_from_md(task_path)

    ctx = {
        "last_created": "",
        "resolved_names": {},
        "resolved_descriptions": {},
        "light_sources_found": [],
        "gpu_available": True,
        "suggested_engine": "EEVEE",
    }

    blocks = [
        "def run():",
        '    ctx = {"resolved_descriptions": {}, "light_sources_found": [], "last_created": ""}',
    ]
    if "task" in task:
        t = task["task"]
        for tr in t.get("transformations", []):
            gen = TRANSFORM_GENERATORS.get(tr["type"])
            if gen:
                lines = gen(tr.get("parameters", {}), ctx)
                blocks.extend(lines)
            else:
                blocks.append(f'    # warning: unknown transformation type "{tr["type"]}"')
    else:
        blocks.append(f'    # warning: no task found in YAML')

    return TEMPLATE_HEADER + "\n".join(blocks) + "\n\n" + TEMPLATE_FOOTER


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python translator.py <task.yaml> [output.py]")
        sys.exit(1)
    task_path = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else "output.py"
    code = translate(task_path)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(code)
    print(f"Generated {output_path}")
